name: CASTAI-Report Generation
 
on:
  # schedule:
    # - cron: "0 17 * * *" #runs daily at 5pm
  workflow_dispatch:    #manual trigger
   inputs:
    start_time:
     description: "Enter Start-Time(YYYY:MM:DDTHH:MM:SS.000000Z)"
     required: true
    end_time:
     description: "Enter End-Time(YYYY:MM:DDTHH:MM:SS.000000Z)"
     required: true
jobs:
 
# JOB 1: Generate clusters_list.txt and all_clusters.xlsx
  generate-clusters:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Install Dependencies
        run: pip install pandas openpyxl

      #creating of directories
      - name: Create cluster_details folder
        run: | 
          mkdir -p cluster_details
          mkdir -p json_output
          mkdir -p xlsx_output
      
      #executing all_clusters.sh
      - name: Run all_clusters Bash Script
        run: |
          chmod +x execute_scripts/all_clusters.sh
          ./execute_scripts/all_clusters.sh
 
      #executing all_clusters.py
      - name: Run all_clusters Python Script
        run: |
          python execute_scripts/all_clusters.py

      #verifying of all_clusters.txt output
      - name: Verify Output
        run: |
          ls -l cluster_details/
          cat cluster_details/clusters_list.txt
 
      #Upload all_clusters.txt and all_clusters.xlsx to artifact
      - name: Upload Cluster Outputs
        uses: actions/upload-artifact@v4
        with:
          name: clusters-data
          path: |
            cluster_details/clusters_list.txt
            json_output/all_clusters.json
            xlsx_output/all_clusters.xlsx
 
 
# JOB 2: Executing other bash_scripts and python_scripts to convert JSON data into excel files 
  process-data:
    runs-on: ubuntu-latest
    needs: generate-clusters
    permissions:
      contents: read
      actions: write
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Download Cluster Data
        uses: actions/download-artifact@v4
        with:
          name: clusters-data
          path: .
 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Install Dependencies
        run: pip install pandas openpyxl narwhals
 
      - name: Run Bash Scripts
        env:
         START_TIME: ${{github.event.inputs.start_time}}
         END_TIME: ${{github.event.inputs.end_time}}
        run: |
          chmod +x execute_scripts/run_bashscripts.sh
          ./execute_scripts/run_bashscripts.sh 
 
      - name: Run Python Scripts
        run: |
          chmod +x execute_scripts/run_pythonscripts.sh
          ./execute_scripts/run_pythonscripts.sh
 
      # Upload everything INCLUDING previous excel
      - name: Upload JSON and Excel Outputs
        uses: actions/upload-artifact@v4
        with:
          name: processed-outputs
          path: |
            json_output/
            xlsx_output/
            cluster_details/clusters_list.txt
 
 
# JOB 3: Generate Final Report
  generate-report:
    runs-on: ubuntu-latest
    needs: process-data
    permissions:
      contents: read
      actions: write
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Download Processed Outputs
        uses: actions/download-artifact@v4
        with:
          name: processed-outputs
 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
 
      - name: Install Dependencies
        run: pip install pandas openpyxl xlsxwriter
 
      - name: Create Report Folder
        run: mkdir -p cast.ai_report

      - name: Merge Excel Files
        run: python execute_scripts/merge_excelfiles.py
 
      - name: Generate HTML Report
        run: python execute_scripts/excel_to_html_report.py
 
      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: castai-final-report
          path: |
            cast.ai_report/
            json_output/
            xlsx_output/
            cluster_details/clusters_list.txt
 
      - name: Success Message
        run: echo "CASTAI-Report Generation completed successfully!"

#JOB 4: Send Email Notification
#   send-email:
#     runs-on: ubuntu-latest
#     need: generate-report

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Download Final Report
#         uses: actions/download-artifact@v4
#         with:
#          name: cast.ai_report

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#          python-version: '3.9'

#       - name: Send Email
#         run: python send_report/send_email.py
#         env:
#          EMAIL_USERNAME: ${{secrets.EMAIL_USERNAME}}
#          EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
#          TO_EMAIL: ${{secrets.TO_EMAIL}}

# #JOB 5: Send Notification to Teams
#   notify-teams:
#     runs-on: ubuntu:latest
#     needs: generate-report

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#          python-version: '3.9'

#       - name: Install Requests Library
#         run: pip install requests

#       - name: Send Notification to Teams
#         run: python send_report/send_teams.py
#         env:
#          TEAMS_WEBHOOK_URL: ${{secrets.TEAMS_WEBHOOK_URL}}
  
 